// @ts-ignore .open-next/worker.js is generated by the OpenNext build.
import nextWorker from './.open-next/worker.js';
import { NeonRoom } from './src/room';

export { NeonRoom };

export default {
  async fetch(request: Request, env: Env, ctx: any) {
    const url = new URL(request.url);
    if (url.pathname === '/ws') {
      if (request.headers.get('Upgrade') !== 'websocket') {
        return new Response('WebSocket upgrade required', { status: 426 });
      }
      const room = (url.searchParams.get('room') || '').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6);
      if (room.length !== 6) return new Response('Invalid room code', { status: 400 });
      const id = env.ROOMS.idFromName(room);
      const stub = env.ROOMS.get(id);
      return stub.fetch(request);
    }
    return nextWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;

interface Env { ROOMS: DurableObjectNamespace<NeonRoom>; }
